# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1015, 484)
        MainWindow.setMinimumSize(QtCore.QSize(1015, 484))
        MainWindow.setMaximumSize(QtCore.QSize(1015, 484))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.backgroundImg = QtWidgets.QLabel(self.centralwidget)
        self.backgroundImg.setGeometry(QtCore.QRect(0, 0, 1016, 440))
        self.backgroundImg.setObjectName("backgroundImg")
        self.buttonUp = QtWidgets.QPushButton(self.centralwidget)
        self.buttonUp.setGeometry(QtCore.QRect(90, 165, 36, 36))
        self.buttonUp.setText("")
        self.buttonUp.setFlat(True)
        self.buttonUp.setObjectName("buttonUp")
        self.buttonLeft = QtWidgets.QPushButton(self.centralwidget)
        self.buttonLeft.setGeometry(QtCore.QRect(53, 202, 36, 36))
        self.buttonLeft.setText("")
        self.buttonLeft.setFlat(True)
        self.buttonLeft.setObjectName("buttonLeft")
        self.buttonRight = QtWidgets.QPushButton(self.centralwidget)
        self.buttonRight.setGeometry(QtCore.QRect(126, 202, 36, 36))
        self.buttonRight.setText("")
        self.buttonRight.setFlat(True)
        self.buttonRight.setObjectName("buttonRight")
        self.buttonDown = QtWidgets.QPushButton(self.centralwidget)
        self.buttonDown.setGeometry(QtCore.QRect(90, 240, 36, 36))
        self.buttonDown.setText("")
        self.buttonDown.setFlat(True)
        self.buttonDown.setObjectName("buttonDown")
        self.buttonB = QtWidgets.QPushButton(self.centralwidget)
        self.buttonB.setGeometry(QtCore.QRect(922, 264, 62, 62))
        self.buttonB.setText("")
        self.buttonB.setFlat(True)
        self.buttonB.setObjectName("buttonB")
        self.buttonA = QtWidgets.QPushButton(self.centralwidget)
        self.buttonA.setGeometry(QtCore.QRect(838, 250, 62, 62))
        self.buttonA.setText("")
        self.buttonA.setFlat(True)
        self.buttonA.setObjectName("buttonA")
        self.buttonX = QtWidgets.QPushButton(self.centralwidget)
        self.buttonX.setGeometry(QtCore.QRect(838, 164, 62, 62))
        self.buttonX.setText("")
        self.buttonX.setFlat(True)
        self.buttonX.setObjectName("buttonX")
        self.buttonY = QtWidgets.QPushButton(self.centralwidget)
        self.buttonY.setGeometry(QtCore.QRect(922, 178, 62, 62))
        self.buttonY.setText("")
        self.buttonY.setFlat(True)
        self.buttonY.setObjectName("buttonY")
        self.buttonReset = QtWidgets.QPushButton(self.centralwidget)
        self.buttonReset.setGeometry(QtCore.QRect(920, 92, 22, 22))
        self.buttonReset.setText("")
        self.buttonReset.setFlat(True)
        self.buttonReset.setObjectName("buttonReset")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1015, 22))
        self.menubar.setObjectName("menubar")
        self.menuFichier = QtWidgets.QMenu(self.menubar)
        self.menuFichier.setObjectName("menuFichier")
        self.menuAide = QtWidgets.QMenu(self.menubar)
        self.menuAide.setObjectName("menuAide")
        self.menuPeripheriques = QtWidgets.QMenu(self.menubar)
        self.menuPeripheriques.setObjectName("menuPeripheriques")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOuvrir = QtWidgets.QAction(MainWindow)
        self.actionOuvrir.setObjectName("actionOuvrir")
        self.actionQuitter = QtWidgets.QAction(MainWindow)
        self.actionQuitter.setObjectName("actionQuitter")
        self.actionA_propos_de = QtWidgets.QAction(MainWindow)
        self.actionA_propos_de.setObjectName("actionA_propos_de")
        self.actionPotentiometres = QtWidgets.QAction(MainWindow)
        self.actionPotentiometres.setObjectName("actionPotentiometres")
        self.actionAccelerometre = QtWidgets.QAction(MainWindow)
        self.actionAccelerometre.setObjectName("actionAccelerometre")
        self.actionGyroscope = QtWidgets.QAction(MainWindow)
        self.actionGyroscope.setObjectName("actionGyroscope")
        self.actionMagnetometre = QtWidgets.QAction(MainWindow)
        self.actionMagnetometre.setObjectName("actionMagnetometre")
        self.actionTests = QtWidgets.QAction(MainWindow)
        self.actionTests.setObjectName("actionTests")
        self.menuFichier.addAction(self.actionOuvrir)
        self.menuFichier.addSeparator()
        self.menuFichier.addAction(self.actionQuitter)
        self.menuAide.addAction(self.actionTests)
        self.menuAide.addAction(self.actionA_propos_de)
        self.menuPeripheriques.addAction(self.actionPotentiometres)
        self.menuPeripheriques.addAction(self.actionAccelerometre)
        self.menuPeripheriques.addAction(self.actionGyroscope)
        self.menuPeripheriques.addAction(self.actionMagnetometre)
        self.menubar.addAction(self.menuFichier.menuAction())
        self.menubar.addAction(self.menuPeripheriques.menuAction())
        self.menubar.addAction(self.menuAide.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Simulateur Arm-Ada"))
        self.backgroundImg.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/images/facade-GB-480x272.png\"/></p></body></html>"))
        self.menuFichier.setTitle(_translate("MainWindow", "&Fichier"))
        self.menuAide.setTitle(_translate("MainWindow", "&Aide"))
        self.menuPeripheriques.setTitle(_translate("MainWindow", "&Peripheriques"))
        self.actionOuvrir.setText(_translate("MainWindow", "&Ouvrir..."))
        self.actionQuitter.setText(_translate("MainWindow", "&Quitter"))
        self.actionA_propos_de.setText(_translate("MainWindow", "A &propos de ..."))
        self.actionPotentiometres.setText(_translate("MainWindow", "Pot&entiometres"))
        self.actionAccelerometre.setText(_translate("MainWindow", "A&ccelerometre"))
        self.actionGyroscope.setText(_translate("MainWindow", "&Gyroscope"))
        self.actionMagnetometre.setText(_translate("MainWindow", "&Magnetometre"))
        self.actionTests.setText(_translate("MainWindow", "Tests..."))
import ressources_rc
