(part "1-1734592-0"
    (packageRef "117345920")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
        (port "5" (symbPinId 5) (portName "5") (portType INOUT))
        (port "6" (symbPinId 6) (portName "6") (portType INOUT))
        (port "7" (symbPinId 7) (portName "7") (portType INOUT))
        (port "8" (symbPinId 8) (portName "8") (portType INOUT))
        (port "9" (symbPinId 9) (portName "9") (portType INOUT))
        (port "10" (symbPinId 10) (portName "10") (portType INOUT))
        (port "MP1" (symbPinId 11) (portName "MP1") (portType INOUT))
        (port "MP2" (symbPinId 12) (portName "MP2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "571-1-1734592-0")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/TE-Connectivity/1-1734592-0?qs=sXy4Dx%2FMQpOH8ogf8%2FvwBg%3D%3D")
    (property "Manufacturer_Name" "TE Connectivity")
    (property "Manufacturer_Part_Number" "1-1734592-0")
    (property "Description" "TE Connectivity FPC 0.5mm Pitch 10 Way Right Angle SMT Female FPC Connector, ZIF Bottom Contact")
    (property "Datasheet_Link" "https://www.te.com/commerce/DocumentDelivery/DDEController?Action=showdoc&DocId=Customer+Drawing%7F1734592%7FC%7Fpdf%7FEnglish%7FENG_CD_1734592_C_C_1734592.pdf%7F1-1734592-8")
    (property "symbolName1" "1-1734592-0")
)
